# Generated by Django 3.2.5 on 2021-11-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0003_auto_20211024_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('n_identificacion', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=13, null=True)),
                ('cargoEmpres', models.CharField(max_length=150, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.empresa')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
