# Generated by Django 3.2 on 2021-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firmaElectronica',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='n_identificacion',
            field=models.CharField(default=1234567891, max_length=13, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_identificacion',
            field=models.CharField(default='CEDULA', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargoEmpres',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
