# Generated by Django 3.2 on 2021-11-25 00:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCreacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='hora',
        ),
        migrations.AddField(
            model_name='documentos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentos',
            name='fechaEmision',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='_file',
            field=models.BinaryField(db_column='file', null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nombreDoc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documento.estado'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipoCreacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documento.tipocreacion'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documento.tipodocumento'),
        ),
    ]
