# Generated by Django 3.2.6 on 2021-09-02 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.TextField(max_length=150)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.PositiveBigIntegerField()),
                ('correo', models.EmailField(max_length=150)),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razonSocial',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
