# Generated by Django 3.2.6 on 2021-10-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField(max_length=1024)),
                ('content_type', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
