# Generated by Django 3.2 on 2021-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211019_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresatemp',
            name='direccion',
        ),
        migrations.AddField(
            model_name='empresatemp',
            name='cargo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='empresatemp',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='empresatemp',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='empresatemp',
            name='correo',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='empresatemp',
            name='razonSocial',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='empresatemp',
            name='telefono',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
