# Generated by Django 3.2.6 on 2021-10-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211019_2234'),
        ('empresa', '0002_firma'),
    ]

    operations = [
    ]
