# Generated by Django 3.2.6 on 2021-10-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20211024_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.BinaryField(db_column='file')),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('nombreDoc', models.CharField(max_length=100)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=25)),
                ('tipoCreacion', models.CharField(max_length=25)),
            ],
        ),
    ]
