# Generated by Django 3.2 on 2021-09-24 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTransaccion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('correo', models.EmailField(blank=True, max_length=150)),
                ('ruc', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('telefono', models.PositiveBigIntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.TextField(max_length=150)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.PositiveBigIntegerField()),
                ('correo', models.EmailField(max_length=150)),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('description', models.TextField(max_length=150)),
                ('documentos', models.TextField(max_length=150)),
                ('reportes', models.IntegerField()),
                ('soporte', models.TextField(max_length=50)),
                ('firma', models.TextField(max_length=50)),
                ('usuarios', models.TextField(max_length=50)),
                ('clientes', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detallePago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.detallepago')),
                ('empresa_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.empresaplan')),
                ('tipoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.tipopago')),
            ],
        ),
        migrations.AddField(
            model_name='empresaplan',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.estadoplan'),
        ),
        migrations.AddField(
            model_name='empresaplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.plan'),
        ),
        migrations.AddField(
            model_name='empresaplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
